/**
 * Słownik marek i modeli masowej sprzedaży w Europie (1960–2026).
 * Obejmuje popularne marki europejskie, japońskie, koreańskie i amerykańskie
 * oraz ich główne linie modelowe (bez wariantów nadwozia/silnika).
 * Nie jest wyczerpującą listą każdej homologacji — do wyszukiwarki części.
 */
export const CARS_BY_BRAND: Record<string, readonly string[]> = {
  Abarth: ["124 Spider", "500", "500e", "595", "695", "Grande Punto", "Punto Evo"],
  "Alfa Romeo": ["145", "146", "147", "156", "159", "164", "166", "33", "75", "90", "Alfasud", "Alfetta", "Brera", "Giulia", "Giulietta", "GT", "GTV", "MiTo", "Spider", "Stelvio", "Tonale"],
  Audi: ["100", "200", "80", "90", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "Cabriolet", "Coupe", "e-tron", "e-tron GT", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "Quattro", "R8", "RS2", "RS3", "RS4", "RS5", "RS6", "RS7", "RS Q3", "RS Q8", "S1", "S3", "S4", "S5", "S6", "S7", "S8", "TT", "V8"],
  Bentley: ["Arnage", "Azure", "Bentayga", "Brooklands", "Continental", "Flying Spur", "Mulsanne"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX2", "iX3", "M1", "M2", "M3", "M4", "M5", "M6", "M8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z1", "Z3", "Z4", "Z8"],
  Buick: ["Century", "Electra", "Enclave", "Encore", "Envision", "LaCrosse", "LeSabre", "Park Avenue", "Regal", "Riviera", "Roadmaster", "Skylark"],
  Cadillac: ["ATS", "BLS", "Brougham", "CT4", "CT5", "CT6", "CTS", "DeVille", "DTS", "Eldorado", "ELR", "Escalade", "Fleetwood", "Lyriq", "Seville", "SRX", "STS", "XT4", "XT5", "XT6", "XTS"],
  Chevrolet: ["Astro", "Aveo", "Beretta", "Blazer", "Camaro", "Caprice", "Captiva", "Cavalier", "Cobalt", "Colorado", "Corsica", "Corvette", "Cruze", "Epica", "Equinox", "Evanda", "Express", "HHR", "Impala", "Kalos", "Lacetti", "Lumina", "Malibu", "Matiz", "Niva", "Nubira", "Orlando", "Rezzo", "S10", "Silverado", "Spark", "Suburban", "Tacuma", "Tahoe", "TrailBlazer", "Trans Sport", "Traverse", "Trax", "Volt"],
  Chrysler: ["200", "300C", "300M", "Aspen", "Crossfire", "Daytona", "Grand Voyager", "LeBaron", "Neon", "New Yorker", "Pacifica", "PT Cruiser", "Sebring", "Stratus", "Town & Country", "Viper", "Voyager"],
  Citroen: ["2CV", "AMI", "AX", "Berlingo", "BX", "C-Crosser", "C-Elysee", "C-ZERO", "C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Aircross", "C4 Cactus", "C4 Picasso", "C4 SpaceTourer", "C5", "C5 Aircross", "C5 X", "C6", "C8", "CX", "DS3", "DS4", "DS5", "Evasion", "Grand C4 SpaceTourer", "GS", "GSA", "Jumper", "Jumpy", "Nemo", "Saxo", "SM", "SpaceTourer", "Synergie", "Visa", "XM", "Xsara", "Xsara Picasso", "ZX"],
  Cupra: ["Ateca", "Born", "Formentor", "Leon", "Tavascan", "Terramar"],
  Dacia: ["Bigster", "Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Pick-Up", "Sandero", "Spring", "Supernova"],
  Daewoo: ["Espero", "Kalos", "Korando", "Lacetti", "Lanos", "Leganza", "Matiz", "Musso", "Nexia", "Nubira", "Rezzo", "Tacuma", "Tico"],
  Daihatsu: ["Applause", "Charade", "Cuore", "Fourtrak", "Gran Move", "Hijet", "Materia", "Move", "Rocky", "Sirion", "Terios", "Trevis", "YRV"],
  Dodge: ["Avenger", "Caliber", "Caravan", "Challenger", "Charger", "Dart", "Durango", "Grand Caravan", "Intrepid", "Journey", "Magnum", "Neon", "Nitro", "RAM", "Stealth", "Stratus", "Viper"],
  DS: ["DS3", "DS3 Crossback", "DS4", "DS4 Crossback", "DS5", "DS7 Crossback", "DS9"],
  Ferrari: ["208", "246", "308", "328", "348", "355", "360", "430", "456", "458", "488", "512", "550", "575", "599", "612", "812", "California", "Daytona", "Dino", "Enzo", "F12", "F355", "F40", "F430", "F50", "F8", "FF", "GTC4Lusso", "LaFerrari", "Mondial", "Portofino", "Purosangue", "Roma", "SF90", "Testarossa"],
  Fiat: ["124", "125p", "126", "127", "128", "130", "131", "500", "500L", "500X", "600", "600e", "Barchetta", "Brava", "Bravo", "Cinquecento", "Coupe", "Croma", "Dino", "Doblo", "Ducato", "Fiorino", "Freemont", "Fullback", "Idea", "Linea", "Marea", "Multipla", "Palio", "Panda", "Punto", "Qubo", "Regata", "Ritmo", "Scudo", "Sedici", "Seicento", "Siena", "Spider", "Stilo", "Strada", "Talento", "Tempra", "Tipo", "Topolino", "Ulysse", "Uno", "X1/9"],
  Ford: ["B-MAX", "Bronco", "C-MAX", "Capri", "Consul", "Cortina", "Cougar", "EcoSport", "Edge", "Escort", "Expedition", "Explorer", "F-150", "Fiesta", "Flex", "Focus", "Fusion", "Galaxy", "Granada", "Granada Scorpio", "GT", "Ka", "Kuga", "Maverick", "Mondeo", "Mustang", "Orion", "Probe", "Puma", "Ranger", "S-MAX", "Scorpio", "Sierra", "Streetka", "Taunus", "Taurus", "Thunderbird", "Tourneo", "Tourneo Connect", "Tourneo Courier", "Tourneo Custom", "Transit", "Transit Connect", "Transit Courier", "Transit Custom", "Windstar"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  Honda: ["Accord", "City", "Civic", "Concerto", "CR-V", "CR-Z", "CRX", "e", "Element", "FR-V", "HR-V", "Insight", "Integra", "Jazz", "Legend", "Logo", "NSX", "Odyssey", "Pilot", "Prelude", "Ridgeline", "S2000", "Shuttle", "Stream", "ZR-V"],
  Hyundai: ["Accent", "Atos", "Bayon", "Coupe", "Elantra", "Equus", "Excel", "Galloper", "Genesis", "Getz", "Grandeur", "H-1", "i10", "i20", "i30", "i40", "IONIQ", "IONIQ 5", "IONIQ 6", "ix20", "ix35", "ix55", "Kona", "Lantra", "Matrix", "Nexo", "Pony", "Santa Fe", "S-Coupe", "Sonata", "Staria", "Terracan", "Trajet", "Tucson", "Veloster", "XG"],
  Infiniti: ["EX", "FX", "G", "I30", "J30", "JX", "M", "Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX56", "QX60", "QX70", "QX80"],
  Isuzu: ["Campo", "D-Max", "Gemini", "Midi", "Rodeo", "Trooper"],
  Jaguar: ["E-Pace", "E-Type", "F-Pace", "F-Type", "I-Pace", "S-Type", "XE", "XF", "XJ", "XJR", "XJS", "XK", "XK8", "X-Type"],
  Jeep: ["Cherokee", "CJ", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Liberty", "Patriot", "Renegade", "Wagoneer", "Wrangler"],
  Kia: ["Carens", "Carnival", "Ceed", "Cerato", "Clarus", "EV3", "EV6", "EV9", "Joice", "Magentis", "Niro", "Opirus", "Optima", "Picanto", "Pride", "ProCeed", "Retona", "Rio", "Roadster", "Sephia", "Shuma", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Venga", "XCeed"],
  Lada: ["110", "111", "112", "1200", "1500", "2101", "2103", "2104", "2105", "2106", "2107", "2110", "2111", "2112", "Granta", "Kalina", "Niva", "Nova", "Priora", "Samara", "Vesta", "XRAY"],
  Lamborghini: ["Aventador", "Countach", "Diablo", "Espada", "Gallardo", "Huracan", "Jalpa", "LM002", "Murcielago", "Revuelto", "Urus", "Veneno"],
  Lancia: ["Beta", "Dedra", "Delta", "Flavia", "Fulvia", "Gamma", "Kappa", "Lybra", "Musa", "Phedra", "Prisma", "Stratos", "Thema", "Thesis", "Voyager", "Ypsilon", "Zeta"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar", "Series I", "Series II", "Series III"],
  Lexus: ["CT", "ES", "GS", "GX", "IS", "LC", "LFA", "LM", "LS", "LX", "NX", "RC", "RX", "RZ", "SC", "UX"],
  Lincoln: ["Aviator", "Continental", "Corsair", "LS", "Mark LT", "MKC", "MKS", "MKT", "MKX", "MKZ", "Navigator", "Nautilus", "Town Car", "Zephyr"],
  Lotus: ["Elan", "Elise", "Eletre", "Emeya", "Emira", "Esprit", "Europa", "Evora", "Excel", "Exige"],
  Maserati: ["222", "3200 GT", "4200", "Biturbo", "Coupe", "Ghibli", "GranCabrio", "GranTurismo", "Grecale", "Levante", "MC20", "Merak", "Quattroporte", "Shamal", "Spyder"],
  Mazda: ["121", "2", "3", "323", "5", "6", "626", "929", "B series", "BT-50", "CX-3", "CX-30", "CX-5", "CX-60", "CX-7", "CX-80", "CX-9", "Demio", "MPV", "MX-3", "MX-30", "MX-5", "MX-6", "Premacy", "Protege", "RX-7", "RX-8", "Tribute", "Xedos 6", "Xedos 9"],
  McLaren: ["540C", "570S", "600LT", "620R", "650S", "675LT", "720S", "750S", "765LT", "Artura", "F1", "GT", "MP4-12C", "P1", "Senna"],
  "Mercedes-Benz": ["190", "A-Class", "AMG GT", "B-Class", "C-Class", "Citan", "CL", "CLA", "CLC", "CLK", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "EQV", "G-Class", "GL", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "M-Class", "Maybach S-Class", "R-Class", "S-Class", "SL", "SLC", "SLK", "SLR", "SLS", "Sprinter", "T-Class", "V-Class", "Vaneo", "Viano", "Vito", "Vito Tourer", "X-Class"],
  MG: ["3", "4 EV", "5", "6", "F", "GS", "HS", "MGA", "MGB", "Midget", "RV8", "TF", "ZR", "ZS", "ZT"],
  Mini: ["Clubman", "Convertible", "Countryman", "Coupe", "Hatch", "Paceman", "Roadster"],
  Mitsubishi: ["3000 GT", "ASX", "Carisma", "Colt", "Cordia", "Eclipse", "Eclipse Cross", "Galant", "Grandis", "i-MiEV", "L200", "Lancer", "Outlander", "Outlander PHEV", "Pajero", "Pajero Pinin", "Pajero Sport", "Space Runner", "Space Star", "Space Wagon", "Starion"],
  Nissan: ["100NX", "200SX", "240SX", "280ZX", "300ZX", "350Z", "370Z", "Almera", "Almera Tino", "Altima", "Ariya", "Bluebird", "Cabstar", "Evalia", "Frontier", "GT-R", "Interstar", "Juke", "Kubistar", "Laurel", "Leaf", "Maxima", "Micra", "Murano", "Navara", "Note", "NV200", "NV300", "NV400", "Pathfinder", "Patrol", "Pixo", "Prairie", "Primastar", "Primera", "Pulsar", "Qashqai", "Qashqai+2", "Sentra", "Serena", "Silvia", "Skyline", "Stanza", "Sunny", "Terrano", "Tiida", "Titan", "Townstar", "Vanette", "X-Trail"],
  Opel: ["Adam", "Agila", "Ampera", "Ampera-e", "Antara", "Ascona", "Astra", "Calibra", "Campo", "Cascada", "Combo", "Commodore", "Corsa", "Crossland", "Frontera", "Grandland X", "GT", "Insignia", "Kadett", "Karl", "Manta", "Meriva", "Mokka", "Monterey", "Monza", "Omega", "Rekord", "Senator", "Signum", "Sintra", "Speedster", "Tigra", "Vectra", "Vita", "Vivaro", "Zafira", "Zafira Life"],
  Peugeot: ["1007", "104", "106", "107", "108", "2008", "204", "205", "206", "207", "208", "3008", "301", "304", "305", "306", "307", "308", "309", "4007", "4008", "404", "405", "406", "407", "408", "5008", "504", "505", "508", "604", "605", "607", "806", "807", "Bipper", "Boxer", "Expert", "Partner", "RCZ", "Rifter", "Traveller"],
  Pontiac: ["6000", "Aztek", "Bonneville", "Fiero", "Firebird", "G5", "G6", "G8", "Grand Am", "Grand Prix", "GTO", "Montana", "Solstice", "Sunbird", "Sunfire", "Tempest", "Trans Sport", "Vibe"],
  Porsche: ["356", "911", "912", "914", "924", "928", "944", "959", "968", "Boxster", "Carrera GT", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
  Renault: ["10", "11", "12", "14", "16", "18", "19", "20", "21", "25", "30", "4", "5", "6", "8", "9", "Alaskan", "Arkana", "Austral", "Avantime", "Captur", "Clio", "Espace", "Express", "Fluence", "Fuego", "Grand Espace", "Grand Scenic", "Kadjar", "Kangoo", "Koleos", "Laguna", "Latitude", "Megane", "Modus", "Rafale", "Rodeo", "Safrane", "Scenic", "Sport Spider", "Symbol", "Talisman", "Trafic", "Twingo", "Twizy", "Vel Satis", "Wind", "Zoe"],
  "Rolls-Royce": ["Camargue", "Corniche", "Cullinan", "Dawn", "Ghost", "Park Ward", "Phantom", "Silver Dawn", "Silver Seraph", "Silver Shadow", "Silver Spirit", "Silver Spur", "Spectre", "Wraith"],
  Rover: ["100", "200", "25", "400", "45", "600", "75", "800", "Metro", "Mini", "Streetwise"],
  Saab: ["9-2X", "9-3", "9-4X", "9-5", "9-7X", "90", "900", "9000", "93", "95", "96", "99"],
  Seat: ["Alhambra", "Altea", "Arona", "Arosa", "Ateca", "Cordoba", "Exeo", "Fura", "Ibiza", "Inca", "Leon", "Malaga", "Marbella", "Mii", "Ronda", "Tarraco", "Toledo"],
  Skoda: ["100", "105", "120", "130", "Citigo", "Elroq", "Enyaq", "Fabia", "Favorit", "Felicia", "Forman", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Popular", "Rapid", "Roomster", "Scala", "Superb", "Yeti"],
  Smart: ["Forfour", "Fortwo", "Roadster"],
  SsangYong: ["Actyon", "Chairman", "Korando", "Kyron", "Musso", "Rexton", "Rodius", "Tivoli", "Torres", "XLV"],
  Subaru: ["BRZ", "Forester", "Impreza", "Justy", "Legacy", "Levorg", "Outback", "SVX", "Tribeca", "Vivio", "WRX", "XT", "XV"],
  Suzuki: ["Across", "Alto", "Baleno", "Cappuccino", "Carry", "Celerio", "Grand Vitara", "Ignis", "Jimny", "Kizashi", "Liana", "Maruti", "Samurai", "S-Cross", "Splash", "Swace", "Swift", "SX4", "Vitara", "Wagon R+", "X-90"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  Toyota: ["4Runner", "86", "Auris", "Avensis", "Aygo", "bZ4X", "C-HR", "Camry", "Carina", "Celica", "Corolla", "Corolla Cross", "Corolla Verso", "Cressida", "Crown", "Dynavan", "Estima", "FJ Cruiser", "GT86", "Hiace", "Highlander", "Hilux", "iQ", "Land Cruiser", "LiteAce", "MR2", "Paseo", "Picnic", "Previa", "Prius", "Prius+", "Proace", "Proace City", "Proace Max", "Proace Verso", "RAV4", "Sequoia", "Sienna", "Starlet", "Supra", "Tacoma", "Tundra", "Urban Cruiser", "Verso", "Verso-S", "Yaris", "Yaris Cross", "Zelas"],
  Vauxhall: ["Adam", "Agila", "Ampera", "Antara", "Astra", "Calibra", "Carlton", "Cascada", "Cavalier", "Chevette", "Combo", "Corsa", "Crossland", "Firenza", "Frontera", "Insignia", "Magnum", "Meriva", "Mokka", "Monaro", "Monterey", "Nova", "Omega", "Royale", "Senator", "Signum", "Tigra", "Vectra", "Victor", "Viva", "Vivaro", "VX220", "VX4/90", "Zafira"],
  Volkswagen: ["Arteon", "Beetle", "Bora", "Caddy", "Corrado", "Crafter", "Eos", "Fox", "Golf", "ID.3", "ID.4", "ID.5", "ID.7", "ID.Buzz", "Jetta", "K70", "Kafer", "LT", "Lupo", "Passat", "Passat CC", "Phaeton", "Polo", "Santana", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Taigo", "Taro", "Tiguan", "Touareg", "Touran", "Transporter", "Type 3", "up!", "Vento", "XL1"],
  Volvo: ["120", "140", "240", "260", "340", "360", "440", "460", "480", "740", "760", "780", "850", "940", "960", "C30", "C70", "EX30", "EX40", "EX90", "S40", "S60", "S70", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"],
};

export const CAR_BRAND_NAMES = Object.keys(CARS_BY_BRAND).sort((a, b) => a.localeCompare(b, "pl"));
